Parameters:
  InstanceType:
      Description: WebServer EC2 instance type
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.nano
        - t2.micro
        - t2.small

  Environment:
    Description: WebServer environment
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
    ConstraintDescription: must be development or production

  ImageId:
    Description: WebServer EC2 image id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2

Rules:
  ProductionInstanceType:
    RuleCondition: !Equals
      - !Ref Environment
      - production
    Assertions:
    - Assert: !Equals [!Ref InstanceType, t2.small]
      AssertDescription: For a production environment, the instance type must be t2.small

  DevelopmentInstanceType:
    RuleCondition: !Equals
      - !Ref Environment
      - development
    Assertions:
    - Assert:
        'Fn::Contains':
          - - t2.nano
            - t2.micro
          - !Ref InstanceType
      AssertDescription: For a development environment, the instance type must be t2.nano or t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
